name: Shared workflow using

on:
  push:
    branches:
      - main
      - develop 

jobs:
  build-push-job:
    uses: Bablu7011/GithubActions-workflows/.github/workflows/docker-ci.yml@v1.0.1

    with:
      image_name: myapp
      tag: ${{ github.ref_name == 'main' && format('prod-{0}', github.sha) || format('staging-{0}', github.sha) }}

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
